[Interface]
PrivateKey = CA+4Vw02N9iC3bJfwwt9K5Nl/YqLBt/4uoTycXQCo10=
Address = 10.0.0.2/24

[Peer]
PublicKey = uPbeIn/8r1+GoyaMwOSSCne/CUepa6zQzMcqsozoP14=
Endpoint = 86.38.204.237:51820
AllowedIPs = 10.0.0.1/32, 10.0.0.0/24
PersistentKeepalive = 25
